version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "=== INSTALL PHASE ==="
      - echo "Node version:"
      - node --version
      - echo "NPM version:"
      - npm --version
      - echo "AWS CLI version:"
      - aws --version

  pre_build:
    commands:
      - echo "=== PRE-BUILD PHASE ==="
      - echo "Installing dependencies..."
      - npm ci
      - echo "Dependencies installed successfully"
      - echo "Checking project files..."
      - ls -la
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "Commit hash:" $COMMIT_HASH

  build:
    commands:
      - echo "=== BUILD PHASE ==="
      - echo Build started on `date`
      - echo "Building Angular application for production..."
      - npm run build
      - echo "Build completed successfully"
      - echo "Listing build output:"
      - ls -la dist/Watering/browser/

  post_build:
    commands:
      - echo "=== POST-BUILD PHASE ==="
      - echo "Deploying to S3 bucket..."
      - aws s3 sync dist/Watering/browser/ s3://watering-style-soft/ --delete --region eu-north-1
      - echo "Files uploaded to S3 successfully"
      - echo "S3 bucket contents:"
      - aws s3 ls s3://watering-style-soft/ --region eu-north-1
      - echo "Invalidating CloudFront cache..."
      - |
        if [ -z "$CLOUDFRONT_DISTRIBUTION_ID" ]; then
          echo "WARNING: CLOUDFRONT_DISTRIBUTION_ID not set, skipping cache invalidation"
        else
          echo "Using CloudFront Distribution ID: $CLOUDFRONT_DISTRIBUTION_ID"
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
            --paths "/*"
          echo "CloudFront cache invalidation completed"
        fi
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: 'dist/Watering/browser'

cache:
  paths:
    - '/root/.npm/**/*'
    - 'node_modules/**/*'
